import "~/styles/globals.css";
import { type Metadata } from "next";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
    return (
        <nav className="flex w-full justify-between items-center border-b p-4 text-xl font-semibold">
            <div >Gallery</div>
            <div >Sign In</div>
        </nav>
    )
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`font-sans ${inter.className}`}>
                <TopNav />
                {children}
            </body>
        </html>
    );
}
